name: Node CI

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - docs
      - asset
      - .vscode
      - .github

  pull_request:
    branches:
      - master
    paths-ignore:
      - docs
      - asset
      - .vscode
      - .github

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # Don't test mac as it's expensive, and Linux tests should cover it
        os: [ubuntu-latest, windows-latest]
        # os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        name: Yarn cache
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: actions/cache@v2
        name: .vscode-test cache
        id: vscode-test-cache
        with:
          path: .vscode-test
          key: ${{ runner.os }}-vscode-test
          restore-keys: |
            ${{ runner.os }}-vscode-test


      - name: Install dependencies and build
        run: |
          yarn --frozen-lockfile
          yarn compile

      - name: Start xvfb
        if: matrix.os == 'ubuntu-latest'
        run: |
          set -e
          /usr/bin/Xvfb :10 -ac >> /tmp/Xvfb.out 2>&1 &
          disown -ar
          echo "Started xvfb"

      - name: Server test
        run: yarn test
        working-directory: server

      - name: E2E test
        run: yarn test:e2e
        env:
          DISPLAY: :10